on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: 0 * * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.ashevillenc.gov/government/city-council-agenda/
          downloaded_filename: agenda.html
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.ashevillenc.gov/government/city-council-meeting-materials/
          downloaded_filename: city-council-meeting-materials.html
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://drive.google.com/uc?export=download&id=1vy7-PdS1_KWZv1HVu_oOvFWzl0KZtuip
          downloaded_filename: 8weekagenda.pdf
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://data-avl.opendata.arcgis.com/datasets/38bdfa06548a45bc9c89c7dddcfc5f31_0.csv
          downloaded_filename: apd_arrests.csv

